### ISSUE TITLE
[linkwarden] NodePort definition is not applied

### ISSUE THREAD

**Issue by titey** [fmjstudios/helm#38]
### Name and Version

fmjstudios/linkwarden 0.3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set `service.type` and `service.nodePort`:
```yaml
# values
# linkwarden-nodeport.yaml
service:
  type: NodePort
  nodePort: 31005
```

deploy with Helm:

```
helm install --version="0.3.3"  --values="linkwarden-nodeport.yaml" linkwarden fmjstudios/linkwarden
```

The service definition does not contain `nodePort: 31005`:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    # [...]
  labels:
    # [...]
  name: linkwarden
  namespace: linkwarden
spec:
  clusterIP: 10.XXX.XXX.XXX
  clusterIPs:
  - 10.XXX.XXX.XXX
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31246  # <== !!!
    port: 8000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: linkwarden
    app.kubernetes.io/name: linkwarden
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

### Are you using any custom parameters or values?

Yes, with values:
```yaml
service:
  type: NodePort
  nodePort: 31005
```

### What is the expected behavior?

The nodePort set into service definition.

### What do you see instead?

The nodePort is not set by the Helm templating.
