### ISSUE TITLE
[paperless-ngx] existingSecret doesn't work for redis

### ISSUE THREAD

**Issue by MyChaOS87** [fmjstudios/helm#8]
### Name and Version

fmjstudios/paperless-ngx 0.2.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Deploy helm chart with existing secret for paperless 

### Are you using any custom parameters or values?

```
paperless:
  domain: <DOMAIN>
  redis:
    host: redis
    existingSecret: redis-secret
tika:
  image:
    tag: 2.9.2.1
redis:
  enabled: false
postgresql:
  enabled: false
```

### What is the expected behavior?

Secret is picked up and fed into ENV of the container

### What do you see instead?

Pod paperless-ngx-0 cannot be started because

secret "paperlessngx-paperless-ngx-redis-auth" not found

### Additional information

the required secrets file is not built, although in '_secrets.tpl' you can already find a special treatment for existing secrets...
